### ISSUE TITLE
phase 2

### ISSUE THREAD

**Issue by FatimaMOUSLIM** [manuvai/risk2023#67]

**Comment by manuvai** [comment]
Done, vu avec captures
![WhatsApp Image 2023-10-27 à 00 00 24_beec9bc3](https://github.com/manuvai/risk2023/assets/44281637/0aa5a256-bd11-41c0-968a-63ee82878f19)
![WhatsApp Image 2023-10-27 à 00 00 30_d319955f](https://github.com/manuvai/risk2023/assets/44281637/7699b8b8-e515-4ec5-b064-e0bf81536a27)
